### PR TITLE
Apple Clone page

### PR DESCRIPTION
**Pull request by blackpintz**
-Used Flex to create the nav and main pages.
-Used CSS grid and float for the footer page.
-Set elements' backgrounds using images and gradients.

### CODE REVIEW

**Comment by majovanilla** [comment]
Hey @blackpintz , 👋

## Good job on this project! 👍

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Always remember to activate your repo in Stickler. I cannot see your linters working!!

- Improve your Readme file. It should be descriptive of the project. You are using the correct template but now you need to fill it with information about your project. You can add details about what you did in this project, why you did it, how you did it...

-Please write meaningful pull request messages. Check this [example](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

- The project should be an exact clone of this [page](https://web.archive.org/web/20140301004610/http://www.apple.com/) Not only you are using a different version of it, but also you are not respecting some of the original elements. (see below)

- The width of the page should not be 100%. Check the spaces on the right and left sides and include them in your clone. 
Your page:
Screenshot from 2020-03-05 20-00-02

Original page:
Screenshot from 2020-03-05 20-00-07

- Change the background images to match the original page (link above). If you want to personalize the page, you can do it after submitting the mandatory version. Inspect the original page and you will see the links to the original images.

- Change the font color of the titles above the main image to be white, as the original page. 
- The text should also be a link.
Your page:
Screenshot from 2020-03-05 19-47-49

Original page:
Screenshot from 2020-03-05 19-47-45

- Your navbar should have links on every element. You need to be able to click them to send you to the right place. Right now, that wouldn't work because you have  `<div>` elements instead of `<a>` elements. Please change them.

- Work on your navbar's look. It should be as close as the original as possible. Right now it looks taller, the apple icon has not the same color, the search bar doesn't change color when you click on it, and there's a hover effect on the search bar that you shouldn't have.
Your navbar:
Screenshot from 2020-03-05 19-54-12

Original one:
Screenshot from 2020-03-05 19-54-18

- You should use the `<input>` tag in the search of your navbar. Read this [article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) about the right use of inputs (spoiler: use them to submit information).

- Your bottom section is not behaving like the original one. After you changed the width of the main image, you will have to adjust the four images of the bottom (they have to be aligned with the main one) and remove the white space between them.
Your page:
Screenshot from 2020-03-05 19-58-19

Original page:
Screenshot from 2020-03-05 19-58-28

- The bottom images should also be links. Please use an `<a>` tag to enclose them.

- The footer should not contain the bottom images, only the links at the end of the page.

- The footer's float info div and the shop-details should contain  `<a>` tags instead of `<small>` or `<span>`  tags. 

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

**Comment by blackpintz** [comment]
-Activated the repo stickler.
-Improved the README file.
-Changed the website to match the original.
-Moved the bottom images to the main tag.
-Put all links in an anchor tag

**Comment by majovanilla** [comment]
Hey @blackpintz , 👋

## You did an *amazing*🌟 ✨ job implementing the required changes on this project! 👊🏻  💯

There are still some details 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Your navbar looks so much better now, but you need to work with the width to avoid the empty space at the end.
Screenshot from 2020-03-06 11-48-41

- Your page still has a 100% width. Play with the width of the body to achieve the look the original page has. 

- The best way to center elements horizontally is to use `margin: auto` use it in your body to make sure everything is in the right position.

- I noticed that you include the text links inside the nav tag, You should use the `<nav>` tag only for the navbar, so please change that. 


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

**Comment by blackpintz** [comment]
-Fixed the width of the body.
-Moved all the text links from the `<nav>` tag to the `<main>` tag.

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello! 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] As the last TSE says: "Your navbar looks so much better now, but you need to work with the width to avoid the empty space at the end.", consider fix this.



- [ ] As the last TSE says: "Your page still has a 100% width. Play with the width of the body to achieve the look the original page has.", consider fix the width as the original page is.





[OPTIONAL]

- [ ] Consider remove the empty big space on the footer





- [ ] Consider adding the demo link working in your readme file.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by blackpintz** [comment]
-Added reset stylesheet and viewport `<meta>` tag to see if it can fix the issue with the navbar and body width.

In case you still see the issues, can we schedule a zoom call? I don't experience the above issues when I run my URL. So I am kinda stuck on what to do about it.

**Comment by davitomix** [comment]
### **Status: Changes required.** 🔍 ♻️ 
****
### Hi @blackpintz. 😄 
### Very good job so far.
### However, the following issues need to be fixed before moving on  👨‍💻  ⬇️ 

****
### Navbar.

- [ ] The first eight elements should be links (to other sections or #).
You have a 'p' inside a 'div', please implement the links using an 'a' tag.
You can do this encapsulating the 'p' into an 'a' tag and styling the 'a' tag.

Screen Shot 2020-03-07 at 6 57 57 PM

- [ ] Navbar input element.

Screen Shot 2020-03-07 at 7 03 12 PM

We still have the issues pointed above by the previous TSE's. 
The blank space at the end of the navbar.
This is because you have a fixed percentage value on the width of the navbar.
So when the webpage width grows, the navbar container still using the same percentage according to the size in that moment.

Screen Shot 2020-03-07 at 7 24 16 PM
I'll recommend you use a 'ul' element instead of divs and put a fixed value on the width of each li element.

Please fix it. 🙏 

- [ ] Body Width.

As the last TSE says: "Your page still has a 100% width. Play with the width of the body to achieve the look the original page has.", consider fix the width as the original page is.

****

### **Please kindly make the changes required and submit a new code review once you are ready!** 🙏 

Happy coding! 😄 💻  
If you have any questions or need help, you can message me on slack (@ David Eli Martinez Garcia).

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Comment by blackpintz** [comment]
-Fixed the navbar.
-Reduced the width of the body.

**Comment by uryelah** [comment]
Hello **Rose Wanjohi**, I'm Sarah, your reviewer for this PR 👩‍🚀 
**Good job going through all the reviews** 🥇 

I have a tip for you. Since it seems that the page width issue is related to having a smaller screen size:
You can press 'Ctrl' and '-' together in your keyboard to make the screen kind of look how it would in a bigger screen just to check if anything changes much.
I myself use this trick a lot since I enjoy working with two windows open side by side.

Considering you did decrease the width like asked and the screen size width was not noted before I'm approving the project. But after that, I encourage you to test the Ctrl- and Ctrl+ in your clone and the original site to check how they look in slightly bigger or smaller screens.

Whenever you are not sure why a TSE is asking for something try to reach out via Slack.

-------
### Your project is approved! 🎊 🥅 💛 
-------
### 
**You may close this Pull Request and merge the changes**

-------

**Good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
